### ISSUE TITLE
`prg_%` pattern breaking parallel builds

### ISSUE THREAD

**Issue by marshallward** [oceans4/MOM_remapping_gpu_2020#17]
Replacing the explicit per-program rules with the `prg_%:` rule is breaking parallel builds, since e.g. `prg_remap`, `prg_remap.o` and `prg_remap.F90` are all getting shoved into the same rule.

There is a race condition in here, and occasionally it will build correctly, but this would seem to be problematic and I recommend we drop the rule.

(And if I had my way, I'd go back to dropping `prg_`!)

**Comment by marshallward** [comment]
Looks like the problem may be more from `prg_%.o:` than `prg_%:`, which doesn't make a whole lot of sense to me, but it is something caused by a glob pattern.

**Comment by adcroft** [comment]
(OK, we'll rename them.)
